### ISSUE TITLE
ArrowOS 安卓11 系统界面无限崩溃

### ISSUE THREAD

**Issue by cokeenet** [577fkj/StatusBarLyric#143]
**环境信息**

模块版本: 4.0
Android版本: 11
屏幕类型: LCD

**在最新的release版本中能否复现**
能
**bug内容**

重启系统界面后系统界面无限崩溃重启 
**复现方法**

激活模块后在模块中重启系统界面

系统ui:https://wwz.lanzouo.com/i48vFzw21uf
完整日志:https://wwz.lanzouo.com/iTOXDzw202b
没有安装其他修改系统界面的模块
（我也不知道是不是系统问题

**Comment by xiaowine** [comment]
> **环境信息**
> 
> 模块版本: 4.0 Android版本: 11 屏幕类型: LCD
> 
> **在最新的release版本中能否复现** 能 **bug内容**
> 
> 重启系统界面后系统界面无限崩溃重启 **复现方法**
> 
> 激活模块后在模块中重启系统界面
> 
> 系统ui:https://wwz.lanzouo.com/i48vFzw21uf 完整日志:https://wwz.lanzouo.com/iTOXDzw202b 没有安装其他修改系统界面的模块 （我也不知道是不是系统问题

日志里并没有模块的报错，请关闭其它模块再试
