### ISSUE TITLE
仅在时间位置显示歌词

### ISSUE THREAD

**Issue by RedSTARO** [577fkj/StatusBarLyric#148]
**环境信息**

模块版本: 4.13
Android版本: 9
屏幕类型: LCD 无挖孔或刘海

**在最新的release版本中能否复现**
能
**bug内容**

状态栏歌词只在时间位置显示
**复现方法**

正常操作开启歌词 百分之百复现

以下是log
----part 2 start----
[ 2022-02-16T11:17:02.017    10067:  8571:  8571 I/LSPosed-Bridge  ] Loading module statusbar.lyric from /data/app/statusbar.lyric-vP8Pf9NAUOF9hisXC5ZSZw==/base.apk
[ 2022-02-16T11:17:02.048    10067:  8571:  8571 I/LSPosed-Bridge  ]   Loading class statusbar.lyric.hook.MainHook
[ 2022-02-16T11:17:02.240    10067:  8571:  8571 I/LSPosed-Bridge  ] StatusBarLyric: Hook android.app.Application.attach Successful
[ 2022-02-16T11:17:02.242    10067:  8571:  8571 I/LSPosed-Bridge  ] StatusBarLyric: Debug已开启
[ 2022-02-16T11:17:02.243    10067:  8571:  8571 I/LSPosed-Bridge  ] StatusBarLyric: statusbar.lyric - 4.1.3.747be96(110 *release)
[ 2022-02-16T11:17:02.243    10067:  8571:  8571 I/LSPosed-Bridge  ] StatusBarLyric: 当前包名: statusbar.lyric
[ 2022-02-16T11:17:26.333    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 收到广播hook: lyric: icon:Netease
[ 2022-02-16T11:17:26.333    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 收到歌词空
[ 2022-02-16T11:17:26.333    10059:  6387:  6660 I/LSPosed-Bridge  ] StatusBarLyric: 网易云状态栏歌词： 网易云音乐正在播放 | false
[ 2022-02-16T11:17:26.455    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 收到广播hook: lyric:作词: 野田洋次郎 icon:Netease
[ 2022-02-16T11:17:26.455    10059:  6387:  6660 I/LSPosed-Bridge  ] StatusBarLyric: 网易云状态栏歌词： 作词: 野田洋次郎 | true
[ 2022-02-16T11:17:26.456    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 关闭图标
[ 2022-02-16T11:17:26.456    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 更新歌词: 作词: 野田洋次郎
[ 2022-02-16T11:17:26.507    10059:  6387:  6660 I/LSPosed-Bridge  ] StatusBarLyric: 网易云状态栏歌词： 网易云音乐正在播放 | false
[ 2022-02-16T11:17:26.517    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 收到广播hook: lyric: icon:Netease
[ 2022-02-16T11:17:26.517    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 收到歌词空
[ 2022-02-16T11:17:26.533    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 关闭歌词
[ 2022-02-16T11:17:26.596    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 收到广播hook: lyric:作曲: 野田洋次郎 icon:Netease
[ 2022-02-16T11:17:26.596    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 关闭图标
[ 2022-02-16T11:17:26.596    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 更新歌词: 作曲: 野田洋次郎
[ 2022-02-16T11:17:26.601    10059:  6387:  6660 I/LSPosed-Bridge  ] StatusBarLyric: 网易云状态栏歌词： 作曲: 野田洋次郎 | true
[ 2022-02-16T11:17:26.698    10059:  6387:  6660 I/LSPosed-Bridge  ] StatusBarLyric: 网易云状态栏歌词： 网易云音乐正在播放 | false
[ 2022-02-16T11:17:26.721    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 收到广播hook: lyric: icon:Netease
[ 2022-02-16T11:17:26.721    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 收到歌词空
[ 2022-02-16T11:17:26.727    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 关闭歌词
[ 2022-02-16T11:17:26.791    10059:  6387:  6660 I/LSPosed-Bridge  ] StatusBarLyric: 网易云状态栏歌词： 二人の間 通り過ぎた風は | true
[ 2022-02-16T11:17:26.792    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 收到广播hook: lyric:二人の間 通り過ぎた風は icon:Netease
[ 2022-02-16T11:17:26.792    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 关闭图标
[ 2022-02-16T11:17:26.792    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 更新歌词: 二人の間 通り過ぎた風は
[ 2022-02-16T11:17:27.739    10009:  6166:  6232 I/LSPosed-Bridge  ] StatusBarLyric: 服务运行: com.netease.cloudmusic
[ 2022-02-16T11:17:28.737    10009:  6166:  6232 I/LSPosed-Bridge  ] StatusBarLyric: 服务运行: com.netease.cloudmusic
[ 2022-02-16T11:17:29.746    10009:  6166:  6232 I/LSPosed-Bridge  ] StatusBarLyric: 服务运行: com.netease.cloudmusic
[ 2022-02-16T11:17:30.736    10009:  6166:  6232 I/LSPosed-Bridge  ] StatusBarLyric: 服务运行: com.netease.cloudmusic
[ 2022-02-16T11:17:31.542    10009:  8807:  8807 I/LSPosed-Bridge  ] Loading module statusbar.lyric from /data/app/statusbar.lyric-vP8Pf9NAUOF9hisXC5ZSZw==/base.apk
[ 2022-02-16T11:17:31.573    10009:  8807:  8807 I/LSPosed-Bridge  ]   Loading class statusbar.lyric.hook.MainHook
[ 2022-02-16T11:17:31.737    10009:  6166:  6232 I/LSPosed-Bridge  ] StatusBarLyric: 服务运行: com.netease.cloudmusic
[ 2022-02-16T11:17:31.756    10009:  8807:  8807 I/LSPosed-Bridge  ] StatusBarLyric: Hook android.app.Application.attach Successful
[ 2022-02-16T11:17:31.760    10009:  8807:  8807 I/LSPosed-Bridge  ] StatusBarLyric: Debug已开启
[ 2022-02-16T11:17:31.760    10009:  8807:  8807 I/LSPosed-Bridge  ] StatusBarLyric: statusbar.lyric - 4.1.3.747be96(110 *release)
[ 2022-02-16T11:17:31.761    10009:  8807:  8807 I/LSPosed-Bridge  ] StatusBarLyric: 当前包名: com.android.systemui
[ 2022-02-16T11:17:31.761    10009:  8807:  8807 I/LSPosed-Bridge  ] StatusBarLyric: 正在hook系统界面
[ 2022-02-16T11:17:31.777    10009:  8807:  8807 I/LSPosed-Bridge  ] StatusBarLyric: 使用系统反色: false
[ 2022-02-16T11:17:31.781    10009:  8807:  8807 I/LSPosed-Bridge  ] StatusBarLyric: Hook com.android.systemui.statusbar.phone.CollapsedStatusBarFragment.onViewCreated Successful
[ 2022-02-16T11:17:31.784    10009:  8807:  8807 I/LSPosed-Bridge  ] StatusBarLyric: hook系统界面结束
[ 2022-02-16T11:17:32.109    10059:  6387:  6660 I/LSPosed-Bridge  ] StatusBarLyric: 网易云状态栏歌词： どこから寂しさを運んできたの | true
[ 2022-02-16T11:17:32.111    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 收到广播hook: lyric:どこから寂しさを運んできたの icon:Netease
[ 2022-02-16T11:17:32.111    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 关闭图标
[ 2022-02-16T11:17:32.113    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 更新歌词: どこから寂しさを運んできたの
[ 2022-02-16T11:17:32.743    10009:  6166:  6232 I/LSPosed-Bridge  ] StatusBarLyric: 服务运行: com.netease.cloudmusic
[ 2022-02-16T11:17:33.750    10009:  6166:  6232 I/LSPosed-Bridge  ] StatusBarLyric: 服务运行: com.netease.cloudmusic
[ 2022-02-16T11:17:34.738    10009:  6166:  6232 I/LSPosed-Bridge  ] StatusBarLyric: 服务运行: com.netease.cloudmusic
[ 2022-02-16T11:17:35.745    10009:  6166:  6232 I/LSPosed-Bridge  ] StatusBarLyric: 服务运行: com.netease.cloudmusic
[ 2022-02-16T11:17:36.313    10059:  6387:  6660 I/LSPosed-Bridge  ] StatusBarLyric: 网易云状态栏歌词： 网易云音乐正在播放 | false
[ 2022-02-16T11:17:36.313    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 收到广播hook: lyric: icon:Netease
[ 2022-02-16T11:17:36.313    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 收到歌词空
[ 2022-02-16T11:17:36.314    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 关闭歌词
[ 2022-02-16T11:17:37.062    10059:  6387:  6660 I/LSPosed-Bridge  ] StatusBarLyric: 网易云状态栏歌词： 网易云音乐正在播放 | false
[ 2022-02-16T11:17:37.063    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 收到广播hook: lyric: icon:Netease
[ 2022-02-16T11:17:37.063    10009:  6166:  6166 I/LSPosed-Bridge  ] StatusBarLyric: 收到歌词空
![Screenshot_20220216-112111](https://user-images.githubusercontent.com/74100786/154243168-b3d44088-9f66-439c-a560-aeb5a88c30b3.png)

**Comment by 577fkj** [comment]
可能是系统的问题限制了时间宽度 暂时无解
