### ISSUE TITLE
其他语言显示不全

### ISSUE THREAD

**Issue by Muratjonn** [577fkj/StatusBarLyric#150]
环境信息
 软件版本:4.13
安卓版本:12

维吾尔族语歌词显示不出来，显示白板    希望作者能看到，修复  ![Screenshot_2022-02-18-13-42-50-125_com.netease.cloudmusic.jpg](https://user-images.githubusercontent.com/92134305/154624834-7335c641-5d96-487d-b85c-19921c9bda9f.jpg)

**Comment by Muratjonn** [comment]
> 请添加支持显示的语言文件

在哪儿？怎么添加？

**Comment by 577fkj** [comment]
使用最新ci版本，自定义字体

**Comment by Muratjonn** [comment]
> 使用最新ci版本，自定义字体

就是3.1.2版本吧？

**Comment by 577fkj** [comment]
https://github.com/577fkj/StatusBarLyric/actions/runs/1857395603
最新ci是这个

**Comment by Muratjonn** [comment]
> https://github.com/577fkj/StatusBarLyric/actions/runs/1857395603
> 最新ci是这个

这个怎么用？好像没看到apk文件

**Comment by Muratjonn** [comment]
Ci版本怎么用？😌

**Comment by Muratjonn** [comment]
> > Ci版本怎么用？😌
> 
> 如果不会下载可以进 https://t.me/StatusBarLyricCI

问题是我没找到字体。。。。

**Comment by 577fkj** [comment]
> > > Ci版本怎么用？😌
> > 
> > 
> > 如果不会下载可以进 https://t.me/StatusBarLyricCI
> 
> 问题是我没找到字体。。。。

自定义 -> 自定义字体

**Comment by Muratjonn** [comment]
> > > > Ci版本怎么用？😌
> > > 
> > > 
> > > 如果不会下载可以进 https://t.me/StatusBarLyricCI
> > 
> > 问题是我没找到字体。。。。
> 
> 自定义 -> 自定义字体

软件设置里的选项我找到了，我没有可用的字体。。。。

**Comment by 577fkj** [comment]
> > > > > Ci版本怎么用？😌
> > > > 
> > > > 
> > > > 如果不会下载可以进 https://t.me/StatusBarLyricCI
> > > 
> > > 
> > > 问题是我没找到字体。。。。
> > 
> > 
> > 自定义 -> 自定义字体
> 
> 软件设置里的选项我找到了，我没有可用的字体。。。。

百度下啊 难不成我还去给你找能显示的字体吗

**Comment by Muratjonn** [comment]
> > > > > > Ci版本怎么用？😌
> > > > > 
> > > > > 
> > > > > 如果不会下载可以进 https://t.me/StatusBarLyricCI
> > > > 
> > > > 
> > > > 问题是我没找到字体。。。。
> > > 
> > > 
> > > 自定义 -> 自定义字体
> > 
> > 软件设置里的选项我找到了，我没有可用的字体。。。。
> 
> 百度下啊 难不成我还去给你找能显示的字体吗

需要什么格式的字体？

**Comment by 577fkj** [comment]
ttf或otf

**Comment by Muratjonn** [comment]
> ttf或otf

OK，谢谢

**Comment by Muratjonn** [comment]
> > ttf或otf
> 
> OK，谢谢

2.12.20版本的MIUI状态栏歌词和最新版【4.1.3.9】的一起发来然后把最新版的总开关关了可以显示维语，最新版换字体只显示很长的歌词短的不行，换了好几个字体都不行，能不能帮我提取一下【2.12.20】版本的字体呢？

**Comment by Muratjonn** [comment]
> > ttf或otf
> 
> OK，谢谢

2.12.20版本的MIUI状态栏歌词和最新版【4.1.3.9】的一起发来然后把最新版的总开关关了可以显示维语，最新版换字体只显示很长的歌词短的不行，换了好几个字体都不行，能不能帮我提取一下【2.12.20】版本的字体呢？

**Comment by Muratjonn** [comment]
> > > ttf或otf
> > 
> > OK，谢谢
> 
> 2.12.20版本的MIUI状态栏歌词和最新版【4.1.3.9】的一起发来然后把最新版的总开关关了可以显示维语，最新版换字体只显示很长的歌词短的不行，换了好几个字体都不行，能不能帮我提取一下【2.12.20】版本的字体呢？

![Screenshot_2022-02-18-21-53-49-368_miui.statusbar.lyric.jpg](https://user-images.githubusercontent.com/92134305/154697762-7af1b2be-fa35-4c79-9303-047d9f2b0c0e.jpg)![Screenshot_2022-02-18-21-53-54-584_statusbar.lyric.jpg](https://user-images.githubusercontent.com/92134305/154697814-80f9ced6-7d80-43f4-aa81-dd6182ce96d1.jpg)

**Comment by 577fkj** [comment]
> > > > ttf或otf
> > > 
> > > 
> > > OK，谢谢
> > 
> > 
> > 2.12.20版本的MIUI状态栏歌词和最新版【4.1.3.9】的一起发来然后把最新版的总开关关了可以显示维语，最新版换字体只显示很长的歌词短的不行，换了好几个字体都不行，能不能帮我提取一下【2.12.20】版本的字体呢？
> 
> ![Screenshot_2022-02-18-21-53-49-368_miui.statusbar.lyric.jpg](https://user-images.githubusercontent.com/92134305/154697762-7af1b2be-fa35-4c79-9303-047d9f2b0c0e.jpg)![Screenshot_2022-02-18-21-53-54-584_statusbar.lyric.jpg](https://user-images.githubusercontent.com/92134305/154697814-80f9ced6-7d80-43f4-aa81-dd6182ce96d1.jpg)

关闭魅族样式可以显示

**Comment by Muratjonn** [comment]
我试试

**Comment by 577fkj** [comment]
维语的靠右特殊性 导致魅族样式无法显示

**Comment by Muratjonn** [comment]
> 维语的靠右特殊性 导致魅族样式无法显示

谢谢谢谢，终于好了
